### PR TITLE
the default rule scope includes the current block

### LINKED ISSUE #114: failing sample execution
the "block_rules" sample is not executed properly:

https://github.com/biscuit-auth/biscuit-rust/actions/runs/3357118911/jobs/5562713872#step:6:83

### PR DESCRIPTION
**Pull request by Geal**
fix #114

### CODE REVIEW

**Comment by divarvel** [comment]
the authorizer and the current block are _always_ trusted, not just when there is no scope annotation.

File: biscuit-auth/src/datalog/origin.rs [hunk 1]
```diff
@@ -72,7 +72,9 @@ impl TrustedOrigins {
         public_key_to_block_id: &HashMap<usize, Vec<usize>>,
     ) -> TrustedOrigins {
         if rule_scopes.is_empty() {
-            return default_origins.clone();
+            let mut origins = default_origins.clone();
+            origins.0.insert(current_block);
```
Comment (divarvel) [inline biscuit-auth/src/datalog/origin.rs:76]:
```suggestion
            origins.0.insert(current_block);
            origins.0.insert(usize::MAX);
```
